# Generated by Django 5.0.7 on 2024-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_url",
        ),
    ]
