# Generated by Django 5.0.7 on 2024-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_remove_video_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
