# Generated by Django 5.0.7 on 2024-07-30 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_group_show_from_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="show_from_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
