# Generated by Django 5.0.7 on 2024-07-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_alter_group_show_from_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="show_from_date",
            new_name="filter_from_date",
        ),
    ]
