# Generated by Django 5.1.3 on 2025-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_alter_group_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="filter_from_date",
        ),
        migrations.AddField(
            model_name="group",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
